osx_image: xcode8.3

language: objective-c

sudo: false

env:
  - XCODE_BUILD_COMMAND="xcodebuild clean test -project DDCarrierDemo.xcodeproj -scheme DDCarrierTests -destination 'platform=iOS Simulator,name=iPhone 6s,OS=10.3.1'"
  - XCODE_BUILD_COMMAND="xcodebuild clean test -project DDCarrierDemo.xcodeproj -scheme DDCarrierTests -destination 'platform=iOS Simulator,name=iPhone SE,OS=9.3'"
  - XCODE_BUILD_COMMAND="xcodebuild clean test -project DDCarrierDemo.xcodeproj -scheme DDCarrierTests -destination 'platform=iOS Simulator,name=iPhone 5s,OS=8.4'"

script:
  - eval $XCODE_BUILD_COMMAND